[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "antifraud"
version = "0.0.1"
description = "Antifraud SDK Client"
requires-python = ">=3.8"
dependencies = [
    "aiohttp>=3.8.0",
    "pydantic>=2.0.0"
]

[project.urls]
Homepage = ""
